/**
 * Server-side accessor for the extracted Social Media Feature Bible registry.
 *
 * The raw data (1082 features + 1082 Wakka Wakka improvements + 100 innovations)
 * lives in src/data/featureBible.json, generated by scripts/extract-feature-bible.mjs.
 *
 * This module is server-only (the JSON is ~1.2MB). The Feature Hub UI reads it
 * through the /api/features route, which paginates and filters server-side.
 * Keep imports of this module on the server (route handlers / server components).
 *
 * The data file is loaded lazily via fs (and cached) rather than imported, so
 * `tsc`/bundlers never have to infer a giant JSON literal type.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { getFeatureStatus, type FeatureStatus } from './featureStatus';

export interface BibleFeature {
  id: string;
  ordinal: number;
  category: string;
  categorySlug: string;
  title: string;
  description: string;
  platforms: string[];
  originalNames: string;
  enhancement: string;
  whyItMatters: string;
}

export interface BibleInnovation {
  id: string;
  ordinal: number;
  category: string;
  categorySlug: string;
  title: string;
  description: string;
  impact: string;
}

export interface BibleCategory {
  index: number;
  name: string;
  slug: string;
  featureCount: number;
  innovationCount: number;
}

export type RegistryItemType = 'feature' | 'innovation';

export interface RegistryItem {
  id: string;
  type: RegistryItemType;
  ordinal: number;
  category: string;
  categorySlug: string;
  title: string;
  description: string;
  /** features only */
  platforms?: string[];
  enhancement?: string;
  whyItMatters?: string;
  /** innovations only */
  impact?: string;
  /** runtime build status */
  status: FeatureStatus['status'];
  href?: string;
  statusNote?: string;
}

interface BibleData {
  generatedAt: string;
  totals: { features: number; improvements: number; innovations: number };
  categories: BibleCategory[];
  features: BibleFeature[];
  innovations: BibleInnovation[];
}

let _data: BibleData | null = null;
function data(): BibleData {
  if (_data) return _data;
  const file = path.join(process.cwd(), 'src', 'data', 'featureBible.json');
  _data = JSON.parse(readFileSync(file, 'utf8')) as BibleData;
  return _data;
}

export function getCategories(): BibleCategory[] {
  return data().categories;
}

export function getTotals() {
  const t = data().totals;
  return {
    features: t.features,
    improvements: t.improvements,
    innovations: t.innovations,
    all: t.features + t.innovations,
  };
}

function toItem(
  base: BibleFeature | BibleInnovation,
  type: RegistryItemType
): RegistryItem {
  const status = getFeatureStatus(base.id);
  const common: RegistryItem = {
    id: base.id,
    type,
    ordinal: base.ordinal,
    category: base.category,
    categorySlug: base.categorySlug,
    title: base.title,
    description: base.description,
    status: status.status,
    href: status.href,
    statusNote: status.note,
  };
  if (type === 'feature') {
    const f = base as BibleFeature;
    common.platforms = f.platforms;
    common.enhancement = f.enhancement;
    common.whyItMatters = f.whyItMatters;
  } else {
    const i = base as BibleInnovation;
    common.impact = i.impact;
  }
  return common;
}

let _allItems: RegistryItem[] | null = null;
function allItems(): RegistryItem[] {
  if (_allItems) return _allItems;
  const d = data();
  _allItems = [
    ...d.features.map((f) => toItem(f, 'feature')),
    ...d.innovations.map((i) => toItem(i, 'innovation')),
  ];
  return _allItems;
}

export interface QueryParams {
  q?: string;
  category?: string; // category slug
  type?: RegistryItemType | 'all';
  status?: FeatureStatus['status'] | 'all';
  page?: number;
  pageSize?: number;
}

export interface QueryResult {
  items: RegistryItem[];
  total: number;
  page: number;
  pageSize: number;
  pageCount: number;
  facets: {
    statusCounts: Record<string, number>;
    typeCounts: Record<string, number>;
  };
}

export function queryRegistry(params: QueryParams): QueryResult {
  const {
    q = '',
    category = 'all',
    type = 'all',
    status = 'all',
    page = 1,
    pageSize = 30,
  } = params;

  const needle = q.trim().toLowerCase();
  const matchesNeedle = (i: RegistryItem) =>
    !needle ||
    i.title.toLowerCase().includes(needle) ||
    i.description.toLowerCase().includes(needle) ||
    (i.enhancement || '').toLowerCase().includes(needle) ||
    (i.platforms || []).some((p) => p.toLowerCase().includes(needle));

  // Scope = everything matching the broad filters (category + search). Facets
  // are computed over this scope so the status/type counts reflect what the
  // user could still narrow to. `items` then applies the narrow type/status.
  const scope = allItems().filter(
    (i) => (category === 'all' || i.categorySlug === category) && matchesNeedle(i)
  );
  const items = scope.filter(
    (i) => (type === 'all' || i.type === type) && (status === 'all' || i.status === status)
  );

  const statusCounts: Record<string, number> = {};
  const typeCounts: Record<string, number> = {};
  for (const i of scope) {
    statusCounts[i.status] = (statusCounts[i.status] || 0) + 1;
    typeCounts[i.type] = (typeCounts[i.type] || 0) + 1;
  }

  const total = items.length;
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  const safePage = Math.min(Math.max(1, page), pageCount);
  const start = (safePage - 1) * pageSize;
  const pageItems = items.slice(start, start + pageSize);

  return {
    items: pageItems,
    total,
    page: safePage,
    pageSize,
    pageCount,
    facets: { statusCounts, typeCounts },
  };
}

export function getItemById(id: string): RegistryItem | undefined {
  return allItems().find((i) => i.id === id);
}

/** Aggregate counts used by the hub header + category cards. */
export function getRegistryStats() {
  const items = allItems();
  const statusCounts: Record<string, number> = {};
  for (const i of items) statusCounts[i.status] = (statusCounts[i.status] || 0) + 1;
  return {
    totals: getTotals(),
    statusCounts,
    categories: getCategories(),
    generatedAt: data().generatedAt,
  };
}
