import {
  User,
  Post,
  Comment,
  Conversation,
  Message,
  Notification,
  Story,
  Community,
  LiveStream,
  AudioRoom,
  Product,
  Hashtag,
  Badge,
} from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    username: "alex_creates",
    email: "alex@example.com",
    displayName: "Alex Rivera",
    bio: "Digital artist & content creator ✨ | Making the internet prettier one post at a time",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=alex",
    coverImage: "https://picsum.photos/seed/alexcover/1200/400",
    website: "https://alexrivera.art",
    location: "Los Angeles, CA",
    isVerified: true,
    verificationTier: "GOLD",
    professionalTier: 'NONE',
    idVerificationStatus: 'UNVERIFIED',
    freeCoursesCreatedThisMonth: 0,
    paidCoursesCreatedThisMonth: 0,
    averageCourseRating: 9.5,
    isPremium: true,
    isPrivate: false,
    twoFactorEnabled: true,
    theme: "dark",
    accentColor: "purple",
    language: "en",
    followersCount: 142800,
    followingCount: 892,
    postsCount: 1247,
    streakDays: 47,
    badges: [
      {
        id: "b1",
        userId: "u1",
        type: "EARLY_ADOPTER",
        name: "Early Adopter",
        description: "Joined in the first month",
        icon: "🌟",
        awardedAt: "2024-01-15",
      },
      {
        id: "b2",
        userId: "u1",
        type: "CREATOR",
        name: "Creator",
        description: "1000+ posts published",
        icon: "🎨",
        awardedAt: "2024-06-01",
      },
    ],
    createdAt: "2024-01-10",
    updatedAt: "2025-06-27",
  },
  {
    id: "u2",
    username: "tech_sam",
    email: "sam@example.com",
    displayName: "Sam Chen",
    bio: "🚀 Software engineer | Open source enthusiast | Building the future",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sam",
    coverImage: "https://picsum.photos/seed/samcover/1200/400",
    website: "https://samchen.dev",
    location: "San Francisco, CA",
    isVerified: true,
    verificationTier: "BLUE",
    professionalTier: 'NONE',
    idVerificationStatus: 'UNVERIFIED',
    freeCoursesCreatedThisMonth: 0,
    paidCoursesCreatedThisMonth: 0,
    averageCourseRating: 0,
    isPremium: true,
    isPrivate: false,
    twoFactorEnabled: false,
    theme: "system",
    accentColor: "blue",
    language: "en",
    followersCount: 28400,
    followingCount: 1240,
    postsCount: 456,
    streakDays: 12,
    badges: [
      {
        id: "b3",
        userId: "u2",
        type: "STREAK_30",
        name: "30-Day Streak",
        description: "Posted 30 days in a row",
        icon: "💫",
        awardedAt: "2025-02-01",
      },
    ],
    createdAt: "2024-03-20",
    updatedAt: "2025-06-27",
  },
  {
    id: "u3",
    username: "maya_lifestyle",
    email: "maya@example.com",
    displayName: "Maya Johnson",
    bio: "Lifestyle blogger | Wellness advocate | 🌿 Plant-based living",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=maya",
    coverImage: "https://picsum.photos/seed/mayacover/1200/400",
    location: "Austin, TX",
    isVerified: false,
    verificationTier: "NONE",
    professionalTier: 'NONE',
    idVerificationStatus: 'UNVERIFIED',
    freeCoursesCreatedThisMonth: 0,
    paidCoursesCreatedThisMonth: 0,
    averageCourseRating: 0,
    isPremium: true,
    isPrivate: false,
    twoFactorEnabled: false,
    theme: "light",
    accentColor: "green",
    language: "en",
    followersCount: 8920,
    followingCount: 2100,
    postsCount: 892,
    streakDays: 5,
    badges: [],
    createdAt: "2024-05-10",
    updatedAt: "2025-06-27",
  },
  {
    id: "u4",
    username: "jordan_music",
    email: "jordan@example.com",
    displayName: "Jordan Blake",
    bio: "🎵 Musician | Producer | Sharing beats & vibes",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=jordan",
    coverImage: "https://picsum.photos/seed/jordancover/1200/400",
    location: "Nashville, TN",
    isVerified: true,
    verificationTier: "BLUE",
    professionalTier: 'NONE',
    idVerificationStatus: 'UNVERIFIED',
    freeCoursesCreatedThisMonth: 0,
    paidCoursesCreatedThisMonth: 0,
    averageCourseRating: 8.8,
    isPremium: true,
    isPrivate: false,
    twoFactorEnabled: true,
    theme: "dark",
    accentColor: "orange",
    language: "en",
    followersCount: 67300,
    followingCount: 450,
    postsCount: 723,
    streakDays: 89,
    badges: [
      {
        id: "b4",
        userId: "u4",
        type: "STREAK_100",
        name: "100-Day Streak",
        description: "Posted 100 days in a row",
        icon: "⚡",
        awardedAt: "2025-04-15",
      },
    ],
    createdAt: "2024-02-14",
    updatedAt: "2025-06-27",
  },
  {
    id: "current",
    username: "you_user",
    email: "you@example.com",
    displayName: "You",
    bio: "Just getting started here! 👋",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=current",
    coverImage: "https://picsum.photos/seed/currentcover/1200/400",
    isVerified: false,
    verificationTier: "NONE",
    professionalTier: 'NONE',
    idVerificationStatus: 'UNVERIFIED',
    freeCoursesCreatedThisMonth: 0,
    paidCoursesCreatedThisMonth: 0,
    averageCourseRating: 0,
    isPremium: true,
    isPrivate: false,
    twoFactorEnabled: false,
    theme: "system",
    accentColor: "blue",
    language: "en",
    followersCount: 12,
    followingCount: 38,
    postsCount: 7,
    streakDays: 3,
    badges: [
      {
        id: "b5",
        userId: "current",
        type: "EARLY_ADOPTER",
        name: "Early Adopter",
        description: "Joined in the first month",
        icon: "🌟",
        awardedAt: "2025-06-01",
      },
    ],
    createdAt: "2025-06-01",
    updatedAt: "2025-06-27",
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: "p1",
    content:
      "Just finished my latest digital artwork — spent 40 hours on this piece! 🎨 What do you think? #DigitalArt #CreativeProcess #ArtOfPhotoFeed",
    author: MOCK_USERS[0],
    authorId: "u1",
    mediaUrls: [
      "https://picsum.photos/seed/art1/800/600",
      "https://picsum.photos/seed/art2/800/600",
    ],
    type: "IMAGE",
    visibility: "PUBLIC",
    isEphemeral: false,
    likesCount: 8924,
    commentsCount: 347,
    sharesCount: 1203,
    viewsCount: 124500,
    hashtags: ["DigitalArt", "CreativeProcess", "ArtOfPhotoFeed"],
    collaborators: [],
    userReaction: "LOVE",
    isBookmarked: true,
    createdAt: "2025-06-26T14:32:00Z",
    updatedAt: "2025-06-26T14:32:00Z",
  },
  {
    id: "p2",
    content:
      "Hot take: The best way to learn coding is to build projects you actually care about. Stop grinding LeetCode and start shipping things. 🚀 Here's what I built this week... #Programming #WebDev #Tech",
    author: MOCK_USERS[1],
    authorId: "u2",
    mediaUrls: ["https://picsum.photos/seed/code1/800/500"],
    type: "IMAGE",
    visibility: "PUBLIC",
    isEphemeral: false,
    likesCount: 2341,
    commentsCount: 189,
    sharesCount: 892,
    viewsCount: 34200,
    hashtags: ["Programming", "WebDev", "Tech"],
    collaborators: [],
    userReaction: undefined,
    createdAt: "2025-06-27T08:15:00Z",
    updatedAt: "2025-06-27T08:15:00Z",
  },
  {
    id: "p3",
    content:
      "Morning wellness routine that changed my life 🌿 Starting each day with intention, not urgency. Details in thread 👇 #Wellness #MindfulLiving #HealthyHabits",
    author: MOCK_USERS[2],
    authorId: "u3",
    mediaUrls: [
      "https://picsum.photos/seed/wellness1/800/800",
      "https://picsum.photos/seed/wellness2/800/800",
      "https://picsum.photos/seed/wellness3/800/800",
    ],
    type: "IMAGE",
    visibility: "PUBLIC",
    isEphemeral: false,
    likesCount: 1567,
    commentsCount: 94,
    sharesCount: 445,
    viewsCount: 21300,
    hashtags: ["Wellness", "MindfulLiving", "HealthyHabits"],
    collaborators: [],
    createdAt: "2025-06-27T06:45:00Z",
    updatedAt: "2025-06-27T06:45:00Z",
  },
  {
    id: "p4",
    content:
      "New track dropping TONIGHT at midnight 🎵🔥 This one hits different. Tag someone who needs to hear it! #NewMusic #Producer #MusicRelease",
    author: MOCK_USERS[3],
    authorId: "u4",
    mediaUrls: ["https://picsum.photos/seed/music1/800/450"],
    type: "VIDEO",
    visibility: "PUBLIC",
    isEphemeral: false,
    likesCount: 12400,
    commentsCount: 2103,
    sharesCount: 5600,
    viewsCount: 890000,
    hashtags: ["NewMusic", "Producer", "MusicRelease"],
    collaborators: [],
    musicTrack: {
      id: "mt1",
      title: "Midnight Frequencies",
      artist: "Jordan Blake",
      audioUrl: "/audio/preview.mp3",
      coverArt: "https://picsum.photos/seed/albumart/400/400",
      duration: 183,
    },
    createdAt: "2025-06-27T10:00:00Z",
    updatedAt: "2025-06-27T10:00:00Z",
  },
  {
    id: "p5",
    content:
      "Working on something exciting with @maya_lifestyle! Collab drop this week 👀✨ #Collab #ComingSoon",
    author: MOCK_USERS[0],
    authorId: "u1",
    mediaUrls: [],
    type: "TEXT",
    visibility: "PUBLIC",
    isEphemeral: false,
    likesCount: 4321,
    commentsCount: 156,
    sharesCount: 234,
    viewsCount: 67800,
    hashtags: ["Collab", "ComingSoon"],
    collaborators: [MOCK_USERS[2]],
    createdAt: "2025-06-27T11:30:00Z",
    updatedAt: "2025-06-27T11:30:00Z",
  },
];

export const MOCK_STORIES: Story[] = [
  {
    id: "s1",
    author: MOCK_USERS[0],
    authorId: "u1",
    mediaUrl: "https://picsum.photos/seed/story1/400/700",
    type: "IMAGE",
    expiresAt: new Date(Date.now() + 20 * 60 * 60 * 1000).toISOString(),
    viewerIds: ["current", "u2"],
    hasViewed: false,
    createdAt: "2025-06-27T07:00:00Z",
  },
  {
    id: "s2",
    author: MOCK_USERS[1],
    authorId: "u2",
    mediaUrl: "https://picsum.photos/seed/story2/400/700",
    type: "IMAGE",
    expiresAt: new Date(Date.now() + 18 * 60 * 60 * 1000).toISOString(),
    viewerIds: ["u1"],
    hasViewed: true,
    createdAt: "2025-06-27T09:00:00Z",
  },
  {
    id: "s3",
    author: MOCK_USERS[3],
    authorId: "u4",
    mediaUrl: "https://picsum.photos/seed/story3/400/700",
    type: "IMAGE",
    expiresAt: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    viewerIds: [],
    hasViewed: false,
    createdAt: "2025-06-27T11:00:00Z",
  },
  {
    id: "s4",
    author: MOCK_USERS[2],
    authorId: "u3",
    mediaUrl: "",
    type: "TEXT",
    textContent: "Good morning! Rise & shine ☀️",
    backgroundColor: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    expiresAt: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    viewerIds: ["current"],
    hasViewed: false,
    createdAt: "2025-06-27T06:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    userId: "current",
    type: "LIKE",
    actor: MOCK_USERS[0],
    actorId: "u1",
    targetId: "p1",
    targetType: "POST",
    isRead: false,
    message: "liked your post",
    link: "/post/p1",
    createdAt: "2025-06-27T12:00:00Z",
  },
  {
    id: "n2",
    userId: "current",
    type: "FOLLOW",
    actor: MOCK_USERS[1],
    actorId: "u2",
    targetId: "current",
    targetType: "USER",
    isRead: false,
    message: "started following you",
    link: "/profile/tech_sam",
    createdAt: "2025-06-27T11:30:00Z",
  },
  {
    id: "n3",
    userId: "current",
    type: "COMMENT",
    actor: MOCK_USERS[3],
    actorId: "u4",
    targetId: "p2",
    targetType: "POST",
    isRead: true,
    message: 'commented: "This is amazing! 🔥"',
    link: "/post/p2",
    createdAt: "2025-06-27T10:15:00Z",
  },
  {
    id: "n4",
    userId: "current",
    type: "MENTION",
    actor: MOCK_USERS[2],
    actorId: "u3",
    targetId: "p3",
    targetType: "POST",
    isRead: true,
    message: "mentioned you in a post",
    link: "/post/p3",
    createdAt: "2025-06-26T20:00:00Z",
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    isGroup: false,
    members: [MOCK_USERS[0], MOCK_USERS[4]],
    admins: [],
    unreadCount: 2,
    lastMessage: {
      id: "m1",
      conversationId: "c1",
      sender: MOCK_USERS[0],
      senderId: "u1",
      content: "Hey! Are you free for a collab this week?",
      isRead: false,
      isDeleted: false,
      createdAt: "2025-06-27T11:45:00Z",
    },
    createdAt: "2025-06-20T10:00:00Z",
  },
  {
    id: "c2",
    name: "Creative Crew",
    isGroup: true,
    avatarUrl: "https://picsum.photos/seed/group1/100/100",
    members: [MOCK_USERS[0], MOCK_USERS[1], MOCK_USERS[2], MOCK_USERS[4]],
    admins: [MOCK_USERS[0]],
    unreadCount: 5,
    lastMessage: {
      id: "m2",
      conversationId: "c2",
      sender: MOCK_USERS[1],
      senderId: "u2",
      content: "Let's plan the next project!",
      isRead: false,
      isDeleted: false,
      createdAt: "2025-06-27T10:30:00Z",
    },
    createdAt: "2025-06-15T14:00:00Z",
  },
];

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: "com1",
    name: "Digital Artists Hub",
    description:
      "A community for digital artists to share work, get feedback, and grow together",
    avatarUrl: "https://picsum.photos/seed/com1/100/100",
    coverImage: "https://picsum.photos/seed/com1cover/1200/400",
    creator: MOCK_USERS[0],
    creatorId: "u1",
    members: [MOCK_USERS[0], MOCK_USERS[2], MOCK_USERS[3]],
    memberCount: 45200,
    moderators: [MOCK_USERS[0]],
    category: "Art & Design",
    isPrivate: false,
    isMember: true,
    createdAt: "2024-03-01",
  },
  {
    id: "com2",
    name: "TechBuilders",
    description:
      "Builders building things. Share your projects, get feedback, find collaborators",
    avatarUrl: "https://picsum.photos/seed/com2/100/100",
    coverImage: "https://picsum.photos/seed/com2cover/1200/400",
    creator: MOCK_USERS[1],
    creatorId: "u2",
    members: [MOCK_USERS[1], MOCK_USERS[0]],
    memberCount: 128400,
    moderators: [MOCK_USERS[1]],
    category: "Technology",
    isPrivate: false,
    isMember: false,
    createdAt: "2024-01-15",
  },
  {
    id: "com3",
    name: "Wellness Warriors",
    description:
      "Supporting each other on the journey to mental and physical wellness",
    avatarUrl: "https://picsum.photos/seed/com3/100/100",
    coverImage: "https://picsum.photos/seed/com3cover/1200/400",
    creator: MOCK_USERS[2],
    creatorId: "u3",
    members: [MOCK_USERS[2], MOCK_USERS[3]],
    memberCount: 23800,
    moderators: [MOCK_USERS[2]],
    category: "Health & Wellness",
    isPrivate: false,
    isMember: true,
    createdAt: "2024-04-20",
  },
];

export const MOCK_LIVE_STREAMS: LiveStream[] = [
  {
    id: "l1",
    host: MOCK_USERS[3],
    hostId: "u4",
    title: "Late Night Beat Making Session 🎵",
    description: "Making beats live, requests welcome!",
    thumbnailUrl: "https://picsum.photos/seed/live1/800/450",
    streamKey: "sk_l1",
    viewerCount: 12400,
    isActive: true,
    coHosts: [],
    giftTotal: 2840,
    comments: [
      {
        id: "lc1",
        user: MOCK_USERS[0],
        message: "🔥🔥🔥",
        type: "COMMENT",
        createdAt: new Date().toISOString(),
      },
      {
        id: "lc2",
        user: MOCK_USERS[2],
        message: "This beat goes crazy!",
        type: "COMMENT",
        createdAt: new Date().toISOString(),
      },
      {
        id: "lc3",
        user: MOCK_USERS[1],
        message: "Sent a gift 🎁 x50",
        type: "GIFT",
        giftAmount: 50,
        createdAt: new Date().toISOString(),
      },
    ],
    createdAt: "2025-06-27T10:00:00Z",
  },
];

export const MOCK_AUDIO_ROOMS: AudioRoom[] = [
  {
    id: "ar1",
    host: MOCK_USERS[1],
    hostId: "u2",
    title: "The Future of AI in Development 🤖",
    description:
      "Panel discussion on how AI tools are changing software development",
    speakers: [MOCK_USERS[1], MOCK_USERS[0]],
    listeners: [MOCK_USERS[2], MOCK_USERS[3]],
    listenerCount: 847,
    isActive: true,
    createdAt: "2025-06-27T09:00:00Z",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "pr1",
    seller: MOCK_USERS[0],
    sellerId: "u1",
    name: "Digital Art Brush Pack Vol. 1",
    description:
      "Professional Procreate brush set with 50+ custom brushes for digital illustration",
    price: 29.99,
    images: [
      "https://picsum.photos/seed/prod1/400/400",
      "https://picsum.photos/seed/prod1b/400/400",
    ],
    category: "Digital Downloads",
    inStock: true,
    rating: 4.8,
    reviewCount: 234,
    createdAt: "2025-06-01",
  },
  {
    id: "pr2",
    seller: MOCK_USERS[3],
    sellerId: "u4",
    name: "Exclusive Sample Pack - Vol 12",
    description: "Hip-hop and R&B samples, 200+ loops and one-shots",
    price: 49.99,
    images: ["https://picsum.photos/seed/prod2/400/400"],
    category: "Music",
    inStock: true,
    rating: 4.9,
    reviewCount: 891,
    createdAt: "2025-06-10",
  },
];

export const MOCK_HASHTAGS: Hashtag[] = [
  { id: "h1", name: "DigitalArt", postCount: 2400000, isTrending: true },
  { id: "h2", name: "Tech", postCount: 18900000, isTrending: true },
  { id: "h3", name: "Wellness", postCount: 890000, isTrending: true },
  { id: "h4", name: "NewMusic", postCount: 4500000, isTrending: true },
  { id: "h5", name: "AI", postCount: 23400000, isTrending: true },
  { id: "h6", name: "Photography", postCount: 34000000, isTrending: false },
  { id: "h7", name: "Coding", postCount: 7800000, isTrending: true },
  { id: "h8", name: "Fitness", postCount: 11200000, isTrending: false },
];

export const CURRENT_USER = MOCK_USERS[4];

import { Course } from "@/types";

export const MOCK_COURSES: Course[] = [
  {
    id: "course-1",
    title: "Advanced React Patterns",
    description: "Learn advanced React patterns for building scalable applications.",
    type: "PAID",
    price: 49.99,
    authorId: MOCK_USERS[0].id,
    author: MOCK_USERS[0],
    rating: 9.5,
    ratingCount: 120,
    thumbnailUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2070&auto=format&fit=crop",
    createdAt: new Date().toISOString(),
  },
  {
    id: "course-2",
    title: "Getting Started with Next.js",
    description: "A free introductory course on Next.js 14 and App Router.",
    type: "FREE",
    authorId: MOCK_USERS[3].id,
    author: MOCK_USERS[3],
    rating: 8.8,
    ratingCount: 45,
    thumbnailUrl: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=2070&auto=format&fit=crop",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  }
];
